---
apiVersion: v1
kind: Namespace
metadata:
  name: trident
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-installer
  namespace: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-installer
  namespace: trident
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: trident-installer
    namespace: trident
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trident-installer
  namespace: trident
spec:
  template:
    spec:
      containers:
        - name: trident-installer
          image: mrlindblom/tridentctl:v20.01.1
          command: ["/tridentctl", " -n trident", "install"]
      restartPolicy: Never
      serviceAccountName: trident-installer
  backoffLimit: 4
